# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproducto', models.IntegerField(max_length=10)),
                ('nombreproductos', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(max_length=200)),
                ('precioproducto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preciototal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lluis.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.IntegerField(max_length=10)),
                ('nombreusuario', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('apellidos', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('fechanacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=30)),
                ('telefono', models.IntegerField(max_length=9)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lluis.Usuarios'),
        ),
    ]
