# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lluis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='correo',
        ),
        migrations.AlterField(
            model_name='productos',
            name='idproducto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellidos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='iduser',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombreusuario',
            field=models.CharField(max_length=20),
        ),
    ]
